### ISSUE TITLE
Plant breeding-- is it possible to ignore sex using matings()?

### ISSUE THREAD

**Issue by labroo2** [cran/optiSel#1]
Hello!

Thank you for your fantastic software. I have a quick question which I hope I have not overlooked elsewhere-- I wish to ignore individuals' sex when using the matings() function to minimize inbreeding in mate allocation, but I don't think it is currently supported.

I am running a plant breeding simulation in which individuals can take either sex. Therefore, I set Sex to NA for all individuals in my candes object as documented, and ran opticont(). Next, I sought the mating combinations which would constrain inbreeding.

To use noffspring(), it is not possible to leave cand$Sex coded as NA due to this line in the function source code:
Sexes <- unique(sex)
It was possible to return the noffspring object anyway by, for example, setting cand$Sex <- "female" for all.

Then, I tried to use the matings() function after resetting cand$Sex <- NA. The function source clearly requires defined sexes, and so I just started messing around with it.

Anyway, if I have not misunderstood anything, if this feature request is within the scope of the package, and if it's a good use of time, would it be possible to allow ignoring sex throughout the package, including the matings() function? I understand if it's not a priority-- thanks again for this tool.

Best wishes,
Marlee

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
